#pragma once

#define VIAL_KEYBOARD_UID {0xED, 0xDE, 0x40, 0x60, 0x97, 0xE8, 0x54, 0x46}
#define VIAL_UNLOCK_COMBO_ROWS {3, 4}
#define VIAL_UNLOCK_COMBO_COLS {5, 5}

#define BILATERAL_COMBINATIONS
#define BILATERAL_COMBINATIONS_LIMIT_CHORD_TO_N_KEYS 4 /* GUI, Alt, Ctrl, Shift */
#define BILATERAL_COMBINATIONS_DELAY_MODS_THAT_MATCH MOD_MASK_GUI
#define BILATERAL_COMBINATIONS_DELAY_MATCHED_MODS_BY 100  /* ms */
#define BILATERAL_COMBINATIONS_ALLOW_CROSSOVER_AFTER 75   /* ms */
#define BILATERAL_COMBINATIONS_ALLOW_SAMESIDED_AFTER 3000 /* ms */